version: "3"

services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "NC-mysql:/var/lib/mysql"
      # - "< Path du script SQL ici >:/docker-entrypoint-initdb.d"
    networks:
      - NCAPI
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s

networks:
  NCAPI:
    driver: bridge

volumes:
  NC-mysql:
    driver: local
